apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/wolfgangunger/jx-angular-io:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/wolfgangunger/jx-angular-io:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: jx-angular-io
        chartPath: charts/jx-angular-io
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/wolfgangunger/jx-angular-io"
          image.tag: "{{.DIGEST_HEX}}"
